name: Build ImmortalWrt for Redmi AX5

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: '是否开启 SSH 远程调试 (true/false)'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-23.05
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 检查代码仓库
      uses: actions/checkout@v3

    - name: 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL https://raw.githubusercontent.com/teddysun/across/master/openwrt/include/apt-install-ubuntu-2204)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 下载源码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: 加载自定义插件 (Feeds)
      run: |
        cd openwrt
        echo "src-git openclash https://github.com/vernesong/OpenClash" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 加载自定义配置 (.config)
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cd openwrt
        make defconfig

    - name: 编译固件 (大约需要 2-3 小时)
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 整理输出文件
      if: steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/ipq60xx/generic/
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: 上传固件至 GitHub Artifacts
      if: steps.compile.outputs.status == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: ImmortalWrt_Redmi_AX5
        path: ${{ env.FIRMWARE }}
